package cli

import "strings"

func teamsControlFallbackHelpContext() string {
	lines := []string{
		"cxp / codex-proxy CLI digest:",
		"- `cxp` or `codex-proxy`: open the local Codex history TUI.",
		"- `cxp run`: launch the original Codex through codex-helper proxy and standard approval handling.",
		"- `cxp run -- codex`: launch the original Codex TUI through CXP's standard approval broker.",
		"- `cxp run --model-profile <name> -- codex`: launch Codex with a saved model profile for this run.",
		"- `cxp proxy`: manage the local proxy profile used by Codex.",
		"- `cxp proxy reset`: clear saved proxy setup and attempt to stop known proxy daemons so the next launch asks whether to configure proxy mode again.",
		"- `cxp model` and `cxp model-profile`: configure built-in model choices or named model profiles.",
		"- `cxp responses serve`: run a local `/v1/responses` adapter backed by an OpenAI-compatible chat upstream.",
		"- `cxp app --model-profile <name>`: launch the Codex desktop app with a saved model profile.",
		"- `cxp beacon`: manage beacon execution profiles and worker leases.",
		"- `cxp upgrade`: upgrade codex-helper itself; use `--version <tag>` for a specific release.",
		"- `cxp history`: inspect local Codex history.",
		"- `cxp skills install-builtin`: install or repair bundled local skills such as the `cxp` usage skill in `$HOME/.agents/skills`.",
		"- `cxp skills migrate`: migrate managed legacy skills from `~/.codex/skills` to `$HOME/.agents/skills`.",
		"- `cxp teams`: manage the Microsoft Teams helper.",
		"",
		"Teams-launched Codex environment note:",
		"- The Teams helper service may not load the user's interactive zsh startup files, so `cxp` can be absent from PATH even when it works in the user's shell.",
		"- If you need to inspect the local helper binary from a Teams Codex turn, prefer `$CODEX_HELPER_CLI_PATH` when set, or `codex-proxy`/`cxp` on PATH.",
		"- Do not treat a missing `cxp` alias as proof that beacon or codex-helper is unavailable.",
		"",
		"cxp model/profile digest:",
		"- `cxp model list`: list built-in model choices and setup status.",
		"- `cxp model setup <model> --api-key-stdin` or `--api-key-env <ENV>`: configure a built-in third-party model choice.",
		"- `cxp model use <model>` and `cxp model doctor [model]`: select or validate a built-in model choice.",
		"- `cxp model-profile setup [name] --provider <provider> --model <model> --api-key-stdin --set-default`: create or update a named model profile.",
		"- Add `--ssh-proxy <proxy-profile>` to a model profile only when upstream model traffic should use an existing SSH proxy profile.",
		"- `cxp model-profile list|doctor|set-default|delete`: inspect, validate, select, or remove saved model profiles.",
		"- `cxp responses serve --base-url <url> --api-key-env <ENV> --model <model>`: expose an OpenAI-compatible chat upstream through a local Responses facade.",
		"- In the TUI, press `Ctrl+A` to toggle Agent Auto Approve (AAA, default off) and `Ctrl+K` for the skills menu.",
		"- Use `cxp run --aaa -- codex` to enable AAA for one launch without changing the saved TUI preference.",
		"",
		"cxp beacon digest:",
		"- Beacon execution profiles are separate from SSH proxy profiles; do not answer `cxp proxy` when the user asks how to configure a beacon profile.",
		"- `cxp beacon profile list`: list beacon profiles.",
		"- `cxp beacon profile create <name> --provider slurm --partition <partition> --image <image> --nodes <n> --gpu <n> --duration <duration> --shared-path <path>`: create a Slurm draft profile. The shared path must be visible to the control machine and allocated workers.",
		"- Add `--query-command <script> --submit-command <script> --cancel-command <script> --renew-command <script>` to store Slurm/LSF adapter commands on the profile without requiring a helper reload.",
		"- Managed Slurm/LSF adapters use the user's normal shell setup by default; add `--adapter-shell direct` when user-shell capture is incompatible or an adapter needs the clean helper service environment.",
		"- If `$SHELL -lic` fails under tcsh/csh, update the profile with `--adapter-shell direct`; profile revisions apply to future turns.",
		"- Custom Slurm/LSF submit adapters must accept `--shared-store` and pass it to the worker as `cxp beacon --store <shared-store> worker ...`; otherwise workers can report `allocation request ... not found` because they read the default store.",
		"- Keep exactly one `exec` in a scheduler submit command; if a site wrapper already prepends `exec`, remove the extra one from the adapter.",
		"- `cxp beacon profile update <name> ...`: create a new profile revision without breaking Work chats already bound to the old revision.",
		"- `cxp beacon profile history <name>`, `cxp beacon profile rollback <name> <revision>`, and `cxp beacon profile gc <name>`: inspect, restore, and safely prune profile revisions.",
		"- `cxp beacon profile create <name> --provider lsf --queue <queue> --shared-path <path>`: create an LSF draft profile.",
		"- `cxp beacon profile create <name> --provider local`: create a local draft profile.",
		"- Add `--proxy ssh_profile --proxy-profile <existing-proxy>` only when the beacon job should use an existing SSH proxy profile.",
		"- Add `--isolation shared` or `--isolation exclusive` to choose the default lease sharing mode.",
		"- `cxp beacon profile doctor <name>`: validate profile fields, shared-path access, and query/submit/cancel/renew adapters without touching the scheduler.",
		"- `cxp beacon profile doctor <name> --smoke`: submit, query, and cancel one real scheduler allocation to verify adapter output and cleanup.",
		"- `cxp beacon profile confirm <name>`: confirm review; incomplete profiles remain draft until doctor requirements pass.",
		"- `cxp beacon profile status <name>` and `cxp beacon status --session <id>`: inspect profile or conversation target state.",
		"- `cxp beacon switch-profile <name> --session <id>`: switch a conversation target after the profile is ready.",
		"- `cxp beacon switch-profile <name> --session <id> --after-current-turn`: defer the switch so an active Codex turn can finish before future turns use the new profile.",
		"- `cxp beacon release <profile|allocation|provider-job|machine> [--force] [--confirm <token>]`: preview and release a beacon resource without requiring the user to know its internal object type. Teams Work `beacon release` detaches only the current chat from shared workers.",
		"- `cxp beacon allocation list|status|cancel|reconcile`: inspect, cancel, and reconcile managed Slurm/LSF allocation requests through configured provider adapters.",
		"- `cxp beacon allocation reconcile-all`: reconcile every allocation, drain stale workers, and recover stale claims.",
		"- The active Teams owner periodically queries provider state and renews due beacon allocations when `*_RENEW` adapters and provider deadlines are available.",
		"- `cxp beacon provider template slurm|lsf`: print a starter scheduler adapter script.",
		"- `cxp beacon worker run-once --machine <id>`: run inside an allocated worker to claim one queued job and publish its terminal result.",
		"- `cxp beacon worker run-once --allocation <request-id> --wait 30m`: register the current Slurm/LSF worker, wait for its Teams job, and publish the terminal result.",
		"- `cxp beacon worker serve --allocation <request-id>`: run a long-lived worker with heartbeats until idle or stopped.",
		"- Beacon workers start the standard approval runtime inside the allocation, so approved commands inherit only scheduler/container devices and mounts already granted to that worker.",
		"- If worker doctor reports `missing codex`, set scheduler PATH or pass worker `--codex-path <codex-or-wrapper>` from the adapter. Use a worker wrapper for path resolution or extra Codex exec flags such as `--skip-git-repo-check`; Teams service `--codex-arg` settings do not automatically reach remote beacon workers. Generated templates honor `CXP_BEACON_CODEX_BIN` as worker `--codex-path`.",
		"- Managed provider adapters can be stored on a profile with `--query-command`, `--submit-command`, `--cancel-command`, and `--renew-command`; Slurm/LSF default to `--adapter-shell user`, while global environment fallback uses `CODEX_HELPER_BEACON_SLURM_QUERY`, `CODEX_HELPER_BEACON_SLURM_SUBMIT`, `CODEX_HELPER_BEACON_SLURM_CANCEL`, `CODEX_HELPER_BEACON_SLURM_RENEW`, `CODEX_HELPER_BEACON_LSF_QUERY`, `CODEX_HELPER_BEACON_LSF_SUBMIT`, `CODEX_HELPER_BEACON_LSF_CANCEL`, `CODEX_HELPER_BEACON_LSF_RENEW`, and `CODEX_HELPER_BEACON_PROVIDER_SHELL_MODE`.",
		"",
		"cxp teams digest:",
		"- `cxp teams setup`: interactive safe setup checklist.",
		"- `cxp teams run`: run the Teams listener in the foreground.",
		"- `cxp teams run --once`: poll Teams once, useful for diagnosis.",
		"- `cxp teams status`: show registry, owner, listener, bridge, poll, and session status.",
		"- `cxp teams doctor`: local Teams helper diagnostics; `--live` checks Graph.",
		"- `cxp teams control --print`: print the bound Teams control chat.",
		"- `cxp teams service bootstrap`: install or repair the background service/watchdog.",
		"- `cxp teams service status`: show OS service/task state.",
		"- `cxp teams service restart --force`: recover local active state, then force a service restart from a terminal.",
		"- `cxp teams service doctor`: diagnose service backend readiness.",
		"- On Linux, service auto mode prefers `systemd --user`; if no user manager is usable, it falls back to `local-supervisor`, which survives terminal close and helper crashes but not machine/container reboot. Enabled or active local-supervisor installs stay sticky to avoid backend flapping; in WSL, the Windows Task backend remains preferred unless local-supervisor is sticky or explicitly selected.",
		"- `cxp teams auth full`: refresh full Teams auth locally.",
		"- `cxp teams auth full-status`: inspect auth cache expiry without printing tokens.",
		"- `cxp teams workflow status|enable|disable|test`: configure optional Teams Workflow notification cards.",
		"- `cxp teams send-file <path> --session <session-id>`: upload a local outbound file and send it as a Teams attachment.",
		"- `cxp teams probe-chat --chat <teams-chat-id-or-link>`: read-only probe of an external Teams chat without binding helper state.",
		"- `cxp teams pause|resume|drain|recover`: local helper lifecycle controls for diagnosis and recovery.",
		"- `cxp teams chat recreate <session-id> --yes`: create and bind a fresh Work chat for an existing helper session.",
		"",
		"Teams control chat digest:",
		"- `projects` / `p`: list workspaces.",
		"- `project <number>` / `p <number>` / bare number after `projects`: open a workspace.",
		"- `sessions` / `s` / `history`: list local Codex sessions in the selected workspace.",
		"- `new <directory>` / `n <directory>`: create a Work chat for a directory.",
		"- `new <directory> --model <profile>` / `new <directory> --model-profile <profile>`: create a Work chat pinned to a model profile.",
		"- `new` / `n`: create a Work chat for the currently selected workspace.",
		"- `continue <number-or-session-id>` / `c <...>`: create/open a Work chat for an existing Codex session.",
		"- `open <number>`: show an existing linked Work chat.",
		"- `status` / `st`: list active Work chats.",
		"- `model list` / `model setup <model>` / `model use <model>` / `model doctor <model>`: manage model profiles from Teams.",
		"- `helper cancel last` / `helper cancel queued` / `helper cancel running` / `helper cancel all`: cancel/drop queued/running control-chat Codex question(s).",
		"- `skills` / `helper skills list`: list installed skill subscriptions.",
		"- `helper skills add <github/gitlab/git-url>`: install skills from a git source and keep them updated in the user agents skills directory.",
		"- `helper skills sync [name]`: sync one skill source, or all sources when no name is given.",
		"- `helper skills push [name]`: review local skill edits; then use `helper skills push confirm` to push from Teams.",
		"- `helper webhook setup`: show Teams Workflow webhook setup.",
		"- `helper update now`: update to the latest stable helper release.",
		"- `helper update prerelease`: update to the newest eligible release or prerelease.",
		"- `helper restart now`: restart the installed Teams helper, including after a release update.",
		"- `helper reload now`: development/source-checkout only; rebuild and reload from a local codex-helper checkout.",
		"",
		"Teams Work chat digest:",
		"- Regular text is sent to Codex as the task.",
		"- `helper status`: check current request state.",
		"- `helper retry last`: retry the last failed/interrupted request.",
		"- `helper cancel last` / `helper cancel queued` / `helper cancel running` / `helper cancel all`: cancel/drop queued/running request(s).",
		"- `helper file <relative-path>`: upload a generated file prepared under the Teams outbound folder.",
		"- `model status` / `model switch <profile>` / `model fork <profile>`: inspect, switch when compatible, or fork the Work chat with another model profile.",
		"- `helper skills list` / `helper skills add <url>` / `helper skills sync [name]` / `helper skills push [name]`: inspect or sync skill subscriptions.",
		"- `helper close`: close the Work chat binding.",
	}
	return strings.TrimSpace(strings.Join(lines, "\n"))
}
