package cli

import "strings"

func teamsControlFallbackHelpContext() string {
	lines := []string{
		"cxp / codex-proxy CLI digest:",
		"- `cxp` or `codex-proxy`: open the local Codex history TUI.",
		"- `cxp run`: launch Codex through codex-helper proxy/yolo handling.",
		"- `cxp proxy`: manage the local proxy profile used by Codex.",
		"- `cxp beacon`: manage beacon execution profiles and worker leases.",
		"- `cxp upgrade`: upgrade codex-helper itself; use `--version <tag>` for a specific release.",
		"- `cxp history`: inspect local Codex history.",
		"- `cxp teams`: manage the Microsoft Teams helper.",
		"",
		"Teams-launched Codex environment note:",
		"- The Teams helper service may not load the user's interactive zsh startup files, so `cxp` can be absent from PATH even when it works in the user's shell.",
		"- If you need to inspect the local helper binary from a Teams Codex turn, prefer `$CODEX_HELPER_CLI_PATH` when set, or `codex-proxy`/`cxp` on PATH.",
		"- Do not treat a missing `cxp` alias as proof that beacon or codex-helper is unavailable.",
		"",
		"cxp beacon digest:",
		"- Beacon execution profiles are separate from SSH proxy profiles; do not answer `cxp proxy` when the user asks how to configure a beacon profile.",
		"- `cxp beacon profile list`: list beacon profiles.",
		"- `cxp beacon profile create <name> --provider slurm --partition <partition> --image <image> --nodes <n> --gpu <n> --duration <duration>`: create a Slurm draft profile.",
		"- `cxp beacon profile create <name> --provider lsf --queue <queue>`: create an LSF draft profile.",
		"- `cxp beacon profile create <name> --provider local`: create a local draft profile.",
		"- Add `--proxy ssh_profile --proxy-profile <existing-proxy>` only when the beacon job should use an existing SSH proxy profile.",
		"- Add `--isolation shared` or `--isolation exclusive` to choose the default lease sharing mode.",
		"- `cxp beacon profile doctor <name>` then `cxp beacon profile confirm <name>`: mark the draft checked and ready.",
		"- `cxp beacon profile status <name>` and `cxp beacon status --session <id>`: inspect profile or conversation target state.",
		"- `cxp beacon switch-profile <name> --session <id>`: switch a conversation target after the profile is ready.",
		"",
		"cxp teams digest:",
		"- `cxp teams setup`: interactive safe setup checklist.",
		"- `cxp teams run`: run the Teams listener in the foreground.",
		"- `cxp teams run --once`: poll Teams once, useful for diagnosis.",
		"- `cxp teams status`: show registry, owner, listener, bridge, poll, and session status.",
		"- `cxp teams doctor`: local Teams helper diagnostics; `--live` checks Graph.",
		"- `cxp teams control --print`: print the bound Teams control chat.",
		"- `cxp teams service bootstrap`: install or repair the background service/watchdog.",
		"- `cxp teams service status`: show OS service/task state.",
		"- `cxp teams service doctor`: diagnose service backend readiness.",
		"- `cxp teams auth full`: refresh full Teams auth locally.",
		"- `cxp teams auth full-status`: inspect auth cache expiry without printing tokens.",
		"",
		"Teams control chat digest:",
		"- `projects` / `p`: list workspaces.",
		"- `project <number>` / `p <number>` / bare number after `projects`: open a workspace.",
		"- `sessions` / `s` / `history`: list local Codex sessions in the selected workspace.",
		"- `new <directory>` / `n <directory>`: create a Work chat for a directory.",
		"- `new` / `n`: create a Work chat for the currently selected workspace.",
		"- `continue <number-or-session-id>` / `c <...>`: create/open a Work chat for an existing Codex session.",
		"- `open <number>`: show an existing linked Work chat.",
		"- `status` / `st`: list active Work chats.",
		"- `skills` / `helper skills list`: list installed skill subscriptions.",
		"- `helper skills add <github/gitlab/git-url>`: install skills from a git source and keep them updated.",
		"- `helper skills sync [name]`: sync one skill source, or all sources when no name is given.",
		"- `helper skills push [name]`: push local skill edits with per-change confirmation.",
		"- `helper webhook setup`: show Teams Workflow webhook setup.",
		"- `helper update now`: update to the latest stable helper release.",
		"- `helper update prerelease`: update to the newest eligible release or prerelease.",
		"- `helper reload now`: load the latest helper code after update.",
		"- `helper restart now`: restart the Teams helper.",
		"",
		"Teams Work chat digest:",
		"- Regular text is sent to Codex as the task.",
		"- `helper status`: check current request state.",
		"- `helper retry last`: retry the last failed/interrupted request.",
		"- `helper cancel last` / `helper cancel all`: cancel/drop queued/running request(s).",
		"- `helper file <relative-path>`: upload a generated file prepared under the Teams outbound folder.",
		"- `helper skills list` / `helper skills add <url>` / `helper skills sync [name]` / `helper skills push [name]`: inspect or sync skill subscriptions.",
		"- `helper close`: close the Work chat binding.",
	}
	return strings.TrimSpace(strings.Join(lines, "\n"))
}
