#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

: "${CODEX_HELPER_TEAMS_GRAPH_429_STRESS_CHATS:=32}"
: "${CODEX_HELPER_TEAMS_GRAPH_429_STRESS_MESSAGES:=6}"
: "${CODEX_HELPER_TEAMS_GRAPH_429_STRESS_ROUNDS:=8}"
: "${CODEX_HELPER_TEAMS_GRAPH_429_STRESS_COUNT:=1}"

echo "Teams Graph 429 stress scale: chats=${CODEX_HELPER_TEAMS_GRAPH_429_STRESS_CHATS} messages=${CODEX_HELPER_TEAMS_GRAPH_429_STRESS_MESSAGES} rounds=${CODEX_HELPER_TEAMS_GRAPH_429_STRESS_ROUNDS} count=${CODEX_HELPER_TEAMS_GRAPH_429_STRESS_COUNT}"

for ((i = 1; i <= CODEX_HELPER_TEAMS_GRAPH_429_STRESS_COUNT; i++)); do
  CODEX_HELPER_TEAMS_GRAPH_429_STRESS=1 \
  CODEX_HELPER_TEAMS_GRAPH_429_STRESS_CHATS="$CODEX_HELPER_TEAMS_GRAPH_429_STRESS_CHATS" \
  CODEX_HELPER_TEAMS_GRAPH_429_STRESS_MESSAGES="$CODEX_HELPER_TEAMS_GRAPH_429_STRESS_MESSAGES" \
  CODEX_HELPER_TEAMS_GRAPH_429_STRESS_ROUNDS="$CODEX_HELPER_TEAMS_GRAPH_429_STRESS_ROUNDS" \
    go test ./internal/teams -count=1 -run 'TestTeamsGraph429Stress(Outbox|Poll)MaintainsAvailabilityAndSuppressesLoopsCI$' -v
done
